# Generated by Django 2.0.5 on 2019-05-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('throtling', models.IntegerField(default=0)),
                ('numThread', models.IntegerField(default=1)),
                ('proxy', models.BooleanField(default=False)),
                ('state', models.CharField(db_index=True, default='new', max_length=150)),
                ('site', models.CharField(db_index=True, max_length=150)),
                ('category', models.CharField(default='new', max_length=150)),
                ('date_start', models.DateTimeField(blank=True)),
                ('date_end', models.DateTimeField(blank=True)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
