# Generated by Django 2.0.5 on 2019-05-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appscrapy', '0002_auto_20190530_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='date_end',
        ),
    ]
