# Generated by Django 2.0.5 on 2019-05-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appscrapy', '0003_remove_jobs_date_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='date_start',
        ),
    ]
