# Generated by Django 2.0.5 on 2019-05-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscrapy', '0004_remove_jobs_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
