# Generated by Django 2.0.5 on 2019-05-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscrapy', '0005_auto_20190530_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
