# Generated by Django 2.0.5 on 2019-05-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscrapy', '0007_auto_20190530_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
