# Generated by Django 2.0.5 on 2019-05-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscrapy', '0009_auto_20190530_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='category',
        ),
        migrations.AddField(
            model_name='jobs',
            name='category',
            field=models.ManyToManyField(related_name='jobs', to='appscrapy.Category'),
        ),
    ]
