# Generated by Django 2.0.5 on 2019-05-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscrapy', '0012_auto_20190531_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='start_url',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='start_url',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
